// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cktzjbbhdgklevhghodq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrdHpqYmJoZGdrbGV2aGdob2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTA5MzYsImV4cCI6MjA2NDUyNjkzNn0.F18tA4Uezv5A1-Lx5Y1SISkJTcD4aikRwBbcE-MyxyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);